/**
 * Defines the contract for a URL provider.
 * Any URL provider class must implement these properties and methods,
 * ensuring consistency and type safety across the application.
 */
export interface IUrlProvider {
  // --- Static URLs ---
  readonly SETTINGS_PAGE_URL: string
  readonly ADD_SETTINGS_PAGE_URL: string
  readonly EDIT_SETTINGS_PAGE_URL: string
  readonly DATA_PAGE_URL: string
  readonly ADD_DATA_PAGE_URL: string
  readonly EDIT_DATA_PAGE_URL: string
  readonly FAQ_CATEGORY_PAGE_URL: string
  readonly TOP_URL: string

  // --- Dynamic URL Generator Methods ---
  getCopySettingPageUrl(id: string): string
  getDetailedCopySettingPageUrl(id: string): string
}

/**
 * A concrete implementation of IUrlProvider that constructs URLs based on a
 * provided path segment
 * This class contains the core logic for building all application URLs.
 */
export class BaseUrlProvider implements IUrlProvider {
  /**
   * The base path for all URLs generated by this instance.
   * e.g., '/members/v3/jcci'
   */
  protected readonly baseUrl: string

  // --- Static URL Properties ---
  public readonly SETTINGS_PAGE_URL: string
  public readonly ADD_SETTINGS_PAGE_URL: string
  public readonly EDIT_SETTINGS_PAGE_URL: string
  public readonly DATA_PAGE_URL: string
  public readonly ADD_DATA_PAGE_URL: string
  public readonly EDIT_DATA_PAGE_URL: string
  public readonly FAQ_CATEGORY_PAGE_URL: string
  public readonly TOP_URL: string

  /**
   * @param segment The dynamic part of the URL path
   */
  constructor(segment: string = '') {
    // 1. Initialize baseUrl first.
    this.baseUrl = `/${segment}`

    // 2. Now, initialize all dependent properties. This resolves the error.
    this.SETTINGS_PAGE_URL = `${this.baseUrl}/master-setting`
    this.ADD_SETTINGS_PAGE_URL = `${this.baseUrl}/master-setting/new`
    this.EDIT_SETTINGS_PAGE_URL = this.SETTINGS_PAGE_URL // Alias for the settings page
    this.DATA_PAGE_URL = `${this.baseUrl}/master-data`
    this.ADD_DATA_PAGE_URL = `${this.baseUrl}/master-data/new`
    this.EDIT_DATA_PAGE_URL = this.DATA_PAGE_URL // Alias for the data page
    this.FAQ_CATEGORY_PAGE_URL = `${this.baseUrl}/faq-category`
    this.TOP_URL = '/members'
  }

  // --- Dynamic URL Method Implementations ---

  /**
   * Generates the URL for the "copy setting" page for a specific item.
   * @param id The unique identifier of the setting to be copied.
   * @returns The fully constructed URL string.
   */
  public getCopySettingPageUrl(id: string): string {
    // This approach is safer than string replacement in components.
    return `${this.baseUrl}/master-setting/${id}/copy/new`
  }

  /**
   * Generates the URL for the detailed "copy setting" view for a specific item.
   * @param id The unique identifier of the setting copy.
   * @returns The fully constructed URL string.
   */
  public getDetailedCopySettingPageUrl(id: string): string {
    return `${this.baseUrl}/master-setting/${id}/copy`
  }
}

// api
export const API_URLS = {
  SETTINGS_API_URL: '/master-setting',
  SETTINGS_CODE_CHECK_API_URL: '/master-setting/check-exist',
  SETTINGS_BULK_UPDATE_API_URL: '/master-setting/bulk',
  DATA_API_URL: '/master-data',
  DATA_CODE_CHECK_API_URL: '/master-data/check-exist',
  DATA_BULK_UPDATE_API_URL: '/master-data/bulk',
  HEALTH_API_URL: '/health',
  SEQUENCE_WITH_PROVIDED_SETTING_API_URL:
    '/sequence/with-provided-setting',
  SEQUENCE_API_URL: '/sequence',
  PARENT_TASK_API_URL: '/tasks/sfn-task-parent',
  TASK_API_URL: '/tasks',
  CCI_API_URL: '/master/cci',
  MASTER_COPY_API_URL: '/master/copy',
}
